# Exclude temporary files
AllCops:
  Exclude:
    - tmp/**/*

# It’s quite readable when we know what we are doing
Lint/AssignmentInCondition:
  Enabled: false

# No need to handle LoadError in Rakefile
Lint/HandleExceptions:
  Exclude:
    - Rakefile

# gemspec is a special snowflake
Metrics/LineLength:
  Max: 100
  Exclude:
    - rom-mongo.gemspec

Gemspec/OrderedDependencies:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# The enforced style doesn’t match Vim’s defaults
Layout/AlignParameters:
  Enabled: false

# UTF-8 is perfectly fine in comments
Style/AsciiComments:
  Enabled: false

# Documentation checked by Inch CI
Style/Documentation:
  Enabled: false

# Early returns have their vices
Style/GuardClause:
  Enabled: false

# Need to be skipped for >-> usage
Style/Lambda:
  Enabled: false

# Multiline block chains are ok
Style/MultilineBlockChain:
  Enabled: false

# Don’t introduce semantic fail/raise distinction
Style/SignalException:
  EnforcedStyle: only_raise

# Need to be skipped for >-> usage
Layout/SpaceAroundOperators:
  Enabled: false

# Accept both single and double quotes
Style/StringLiterals:
  Enabled: false

# Allow def self.foo; @foo; end
Style/TrivialAccessors:
  Enabled: false

# This is a shim file for those who require 'rom-mongo'
Naming/FileName:
  Exclude:
    - lib/rom-mongo.rb
